name: base
channels:
  - defaults
  - conda-forge
  - opensim-org
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - anaconda-anon-usage=0.4.4
  - anyio=4.6.2
  - aom=3.6.0
  - appnope=0.1.3
  - archspec=0.2.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=19.0.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=24.2.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.11.212
  - babel=2.11.0
  - beautifulsoup4=4.12.3
  - bleach=6.2.0
  - blosc=1.21.5
  - boltons=23.0.0
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - c-blosc2=2.12.0
  - ca-certificates=2025.10.5
  - certifi=2025.10.5
  - cffi=1.17.1
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=3.3.2
  - comm=0.2.1
  - conda=25.7.0
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=24.11.1
  - conda-package-handling=2.3.0
  - conda-package-streaming=0.10.0
  - contourpy=1.2.0
  - cpp-expected=1.1.0
  - cryptography=43.0.0
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - datasets=2.19.1
  - dav1d=1.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.8
  - distro=1.9.0
  - executing=0.8.3
  - expat=2.6.3
  - filelock=3.13.1
  - fmt=11.0.2
  - fonttools=4.51.0
  - freetype=2.12.1
  - frozendict=2.4.2
  - frozenlist=1.5.0
  - fsspec=2024.3.1
  - gflags=2.2.2
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - glog=0.5.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - h11=0.14.0
  - hdf5=1.14.3
  - httpcore=1.0.2
  - httpx=0.27.0
  - huggingface_hub=0.24.6
  - icu=73.1
  - idna=3.7
  - imagecodecs=2023.1.23
  - imageio=2.33.1
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.27.0
  - ipywidgets=8.1.2
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.9.25
  - jsonpatch=1.33
  - jsonpointer=2.1
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.2.5
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - jxrlib=1.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lazy_loader=0.4
  - lcms2=2.12
  - lerc=3.0
  - libabseil=20240116.2
  - libaec=1.1.4
  - libarchive=3.7.7
  - libavif=0.11.1
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang13=14.0.6
  - libcurl=8.11.1
  - libdeflate=1.17
  - libevent=2.1.12
  - libexpat=2.6.3
  - libffi=3.4.4
  - libglib=2.78.4
  - libgrpc=1.62.2
  - libiconv=1.16
  - libmamba=2.0.5
  - libmambapy=2.0.5
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libpq=17.0
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libsolv=0.7.30
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libtorch=2.5.1
  - libuv=1.48.0
  - libwebp-base=1.3.2
  - libxml2=2.13.5
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - lz4-c=1.9.4
  - mamba=2.0.5
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - menuinst=2.1.2
  - mistune=2.0.4
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.1.0
  - multiprocess=0.70.15
  - nbclient=0.8.0
  - nbconvert=7.16.4
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - networkx=3.3
  - nlohmann_json=3.11.3
  - notebook=7.2.2
  - notebook-shim=0.2.3
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.5.4
  - opentelemetry-api=1.37.0
  - orc=2.0.1
  - overrides=7.4.0
  - packaging=24.1
  - pandas=2.2.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre2=10.42
  - pexpect=4.8.0
  - pillow=11.0.0
  - pip=24.2
  - platformdirs=3.10.0
  - plotly=5.24.1
  - pluggy=1.0.0
  - ply=3.11
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - propcache=0.2.0
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-cpuinfo=9.0.0
  - pyarrow=19.0.0
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.21
  - pygments=2.15.1
  - pyparsing=3.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - pytables=3.8.0
  - python=3.12.2
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python-xxhash=3.5.0
  - pytorch=2.5.1
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - qtconsole=5.6.0
  - qtpy=2.4.1
  - re2=2022.04.01
  - referencing=0.30.2
  - regex=2024.11.6
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - safetensors=0.4.5
  - scikit-image=0.24.0
  - scikit-learn=1.5.2
  - send2trash=1.8.2
  - setuptools=75.1.0
  - simdjson=3.11.3
  - sip=6.7.12
  - six=1.16.0
  - sleef=3.5.1
  - sniffio=1.3.0
  - soupsieve=2.5
  - spdlog=1.15.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - sympy=1.14.0
  - tenacity=9.0.0
  - terminado=0.17.1
  - threadpoolctl=3.5.0
  - tifffile=2023.4.12
  - tinycss2=1.2.1
  - tk=8.6.14
  - tokenizers=0.20.1
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - transformers=4.45.2
  - truststore=0.8.0
  - typing_extensions=4.11.0
  - tzdata=2024b
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - utf8proc=2.6.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - widgetsnbextension=4.0.13
  - xxhash=0.8.0
  - xz=5.4.6
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - yarl=1.18.0
  - zeromq=4.3.5
  - zfp=1.0.0
  - zipp=3.21.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.3.0
      - alabaster==0.7.16
      - albumentations==1.4.3
      - altgraph==0.17.4
      - app-model==0.2.8
      - appdirs==1.4.4
      - astunparse==1.6.3
      - autograd==1.8.0
      - autograd-gamma==0.5.0
      - build==1.3.0
      - cachey==0.2.1
      - chardet==5.2.0
      - click==8.3.0
      - cloudpickle==3.1.1
      - dask==2025.10.0
      - dask-image==2024.5.3
      - deeplabcut==3.0.0rc13
      - dlclibrary==0.0.11
      - docstring-parser==0.17.0
      - docutils==0.17.1
      - einops==0.8.1
      - etils==1.13.0
      - ffmpeg==1.4
      - filterpy==1.4.5
      - flatbuffers==25.2.10
      - flexcache==0.3
      - flexparser==0.4
      - formulaic==1.1.1
      - freetype-py==2.5.1
      - gast==0.6.0
      - glfw==2.10.0
      - google-pasta==0.2.0
      - grpcio==1.73.1
      - h5py==3.14.0
      - heapdict==1.0.1
      - hmmlearn==0.3.3
      - hsluv==5.0.4
      - imageio-ffmpeg==0.6.0
      - imagesize==1.4.1
      - imgaug==0.4.0
      - importlib-resources==6.5.2
      - in-n-out==0.2.1
      - interface-meta==1.3.0
      - islp==0.4.0
      - keras==3.10.0
      - libclang==18.1.1
      - lifelines==0.30.0
      - lightning-utilities==0.14.3
      - llvmlite==0.46.0b1
      - locket==1.0.0
      - loguru==0.7.3
      - lxml==5.4.0
      - lxml-html-clean==0.4.3
      - macholib==1.16.3
      - magicgui==0.10.1
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - matplotlib==3.8.4
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - modulegraph==0.19.6
      - mujoco==3.3.7
      - namex==0.1.0
      - napari==0.4.18
      - napari-console==0.1.4
      - napari-deeplabcut==0.2.1.7
      - napari-plugin-engine==0.2.0
      - napari-svg==0.2.1
      - natsort==8.4.0
      - nibabel==5.3.2
      - npe2==0.7.9
      - nuitka==2.7.11
      - numba==0.63.0b1
      - numpydoc==1.5.0
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - opt-einsum==3.4.0
      - optree==0.16.0
      - ordered-set==4.1.0
      - partd==1.4.2
      - patsy==1.0.1
      - pdf2image==1.17.0
      - pims==0.7
      - pint==0.25
      - pooch==1.8.2
      - progressbar2==4.5.0
      - protobuf==5.29.5
      - psygnal==0.15.0
      - py2app==0.28.8
      - pycocotools==2.0.10
      - pyconify==0.2.1
      - pydantic==1.10.24
      - pydantic-compat==0.1.2
      - pygam==0.9.1
      - pyinstaller==6.14.2
      - pyinstaller-hooks-contrib==2025.5
      - pyopengl==3.1.10
      - pyproject-hooks==1.2.0
      - pyside6==6.10.0
      - pyside6-addons==6.10.0
      - pyside6-essentials==6.10.0
      - python-utils==3.9.1
      - pytorch-lightning==2.5.1.post0
      - qdarkstyle==3.1
      - rich==14.0.0
      - scipy==1.11.4
      - seaborn==0.13.2
      - shapely==2.1.2
      - shellingham==1.5.4
      - shiboken6==6.10.0
      - slicerator==1.1.0
      - snowballstemmer==3.0.1
      - sphinx==4.5.0
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - statsmodels==0.14.4
      - superqt==0.7.6
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - termcolor==3.1.0
      - timm==1.0.20
      - tomli-w==1.2.0
      - toolz==1.1.0
      - torch==2.9.0
      - torchmetrics==1.7.2
      - torchvision==0.24.0
      - typer==0.20.0
      - typing-extensions==4.12.2
      - vispy==0.12.2
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xlrd==2.0.2
prefix: /Users/chen/miniconda3
