name: base
channels:
  - defaults
  - conda-forge
  - opensim-org
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - aiohappyeyeballs=2.4.4=py312hca03da5_0
  - aiohttp=3.11.10=py312h80987f9_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - anaconda-anon-usage=0.4.4=py312hd6b623d_100
  - anyio=4.6.2=py312hca03da5_0
  - aom=3.6.0=h313beb8_0
  - appnope=0.1.3=py312hca03da5_1001
  - archspec=0.2.3=pyhd3eb1b0_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py312h80987f9_0
  - arrow-cpp=19.0.0=h0b7d223_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py312hca03da5_0
  - attrs=24.2.0=py312hca03da5_0
  - aws-c-auth=0.6.19=h80987f9_0
  - aws-c-cal=0.5.20=h80987f9_0
  - aws-c-common=0.8.5=h80987f9_0
  - aws-c-compression=0.2.16=h80987f9_0
  - aws-c-event-stream=0.2.15=h313beb8_0
  - aws-c-http=0.6.25=h80987f9_0
  - aws-c-io=0.13.10=h80987f9_0
  - aws-c-mqtt=0.7.13=h80987f9_0
  - aws-c-s3=0.1.51=h80987f9_0
  - aws-c-sdkutils=0.1.6=h80987f9_0
  - aws-checksums=0.1.13=h80987f9_0
  - aws-crt-cpp=0.18.16=h313beb8_0
  - aws-sdk-cpp=1.11.212=hdd7fb2f_0
  - babel=2.11.0=py312hca03da5_0
  - beautifulsoup4=4.12.3=py312hca03da5_0
  - blas=1.0=openblas
  - bleach=6.2.0=py312hca03da5_0
  - blosc=1.21.5=h9c252e8_1
  - boltons=23.0.0=py312hca03da5_0
  - boost-cpp=1.82.0=h48ca7d4_2
  - bottleneck=1.4.2=py312ha86b861_0
  - brotli=1.0.9=h80987f9_8
  - brotli-bin=1.0.9=h80987f9_8
  - brotli-python=1.0.9=py312h313beb8_8
  - brunsli=0.1=hc377ac9_1
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.19.1=h80987f9_0
  - c-blosc2=2.12.0=ha57e6be_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - certifi=2025.10.5=py312hca03da5_0
  - cffi=1.17.1=py312h3eb5a62_0
  - cfitsio=3.470=h7f6438f_7
  - charls=2.2.0=hc377ac9_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.1=py312hca03da5_0
  - conda=25.7.0=py312hca03da5_0
  - conda-content-trust=0.2.0=py312hca03da5_1
  - conda-libmamba-solver=24.11.1=pyhd8ed1ab_0
  - conda-package-handling=2.3.0=py312hca03da5_0
  - conda-package-streaming=0.10.0=py312hca03da5_0
  - contourpy=1.2.0=py312h48ca7d4_0
  - cpp-expected=1.1.0=hffc8910_0
  - cryptography=43.0.0=py312hd4332d6_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h9131b1a_1
  - datasets=2.19.1=py312hca03da5_0
  - dav1d=1.2.1=h80987f9_0
  - debugpy=1.6.7=py312h313beb8_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - dill=0.3.8=py312hca03da5_0
  - distro=1.9.0=py312hca03da5_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.3=h313beb8_0
  - filelock=3.13.1=py312hca03da5_0
  - fmt=11.0.2=h420ef59_0
  - fonttools=4.51.0=py312h80987f9_0
  - freetype=2.12.1=h1192e45_0
  - frozendict=2.4.2=py312hca03da5_0
  - frozenlist=1.5.0=py312h80987f9_0
  - fsspec=2024.3.1=py312hca03da5_0
  - gettext=0.21.0=hbdbcc25_2
  - gflags=2.2.2=h313beb8_1
  - giflib=5.2.2=h80987f9_0
  - glib=2.78.4=h313beb8_0
  - glib-tools=2.78.4=h313beb8_0
  - glog=0.5.0=h313beb8_1
  - gmp=6.3.0=h313beb8_0
  - gmpy2=2.2.1=py312h5c1b81f_0
  - gst-plugins-base=1.14.1=h313beb8_1
  - gstreamer=1.14.1=h80987f9_1
  - h11=0.14.0=py312hca03da5_0
  - hdf5=1.14.3=nompi_hec07895_105
  - httpcore=1.0.2=py312hca03da5_0
  - httpx=0.27.0=py312hca03da5_0
  - huggingface_hub=0.24.6=py312hca03da5_0
  - icu=73.1=h313beb8_0
  - idna=3.7=py312hca03da5_0
  - imagecodecs=2023.1.23=py312h75b721f_1
  - imageio=2.33.1=py312hca03da5_0
  - importlib-metadata=8.5.0=py312hca03da5_0
  - ipykernel=6.29.5=py312hca03da5_0
  - ipython=8.27.0=py312hca03da5_0
  - ipywidgets=8.1.2=py312hca03da5_0
  - jedi=0.19.1=py312hca03da5_0
  - jinja2=3.1.4=py312hca03da5_1
  - joblib=1.4.2=py312hca03da5_0
  - jpeg=9e=h80987f9_3
  - json5=0.9.25=py312hca03da5_0
  - jsonpatch=1.33=py312hca03da5_1
  - jsonpointer=2.1=pyhd3eb1b0_0
  - jsonschema=4.23.0=py312hca03da5_0
  - jsonschema-specifications=2023.7.1=py312hca03da5_0
  - jupyter=1.0.0=py312hca03da5_9
  - jupyter-lsp=2.2.0=py312hca03da5_0
  - jupyter_client=8.6.0=py312hca03da5_0
  - jupyter_console=6.6.3=py312hca03da5_1
  - jupyter_core=5.7.2=py312hca03da5_0
  - jupyter_events=0.10.0=py312hca03da5_0
  - jupyter_server=2.14.1=py312hca03da5_0
  - jupyter_server_terminals=0.4.4=py312hca03da5_1
  - jupyterlab=4.2.5=py312hca03da5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py312hca03da5_0
  - jupyterlab_widgets=3.0.13=py312hca03da5_0
  - jxrlib=1.1=h1a28f6b_2
  - kiwisolver=1.4.4=py312h313beb8_0
  - krb5=1.20.1=hf3e1bf2_1
  - lazy_loader=0.4=py312hca03da5_0
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libabseil=20240116.2=cxx17_h313beb8_0
  - libaec=1.1.4=h51d1e36_0
  - libarchive=3.7.7=h8f13d7a_0
  - libavif=0.11.1=h80987f9_0
  - libboost=1.82.0=h0bc93f9_2
  - libbrotlicommon=1.0.9=h80987f9_8
  - libbrotlidec=1.0.9=h80987f9_8
  - libbrotlienc=1.0.9=h80987f9_8
  - libclang13=14.0.6=default_h24352ff_1
  - libcurl=8.11.1=hde089ae_0
  - libcxx=19.1.6=ha82da77_1
  - libdeflate=1.17=h80987f9_1
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libevent=2.1.12=h02f6b3c_1
  - libexpat=2.6.3=hf9b8971_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=14_2_0_h6c33f7e_103
  - libgfortran5=14.2.0=h6c33f7e_103
  - libglib=2.78.4=h0a96307_0
  - libgrpc=1.62.2=h62f6fdd_0
  - libiconv=1.16=h80987f9_3
  - libllvm14=14.0.6=h19fdd8a_4
  - libmamba=2.0.5=hdf44a08_1
  - libmambapy=2.0.5=py312h86ad8a2_1
  - libnghttp2=1.57.0=h62f6fdd_0
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libpq=17.0=h02f6b3c_0
  - libprotobuf=4.25.3=h514c7bf_0
  - libsodium=1.0.18=h1a28f6b_0
  - libsolv=0.7.30=h514c7bf_1
  - libsqlite=3.46.0=hfb93653_0
  - libssh2=1.11.1=h3e2b118_0
  - libthrift=0.15.0=h73c2103_2
  - libtiff=4.5.1=h313beb8_0
  - libtorch=2.5.1=gpu_mps_h82d5d13_202
  - libuv=1.48.0=h80987f9_0
  - libwebp-base=1.3.2=h80987f9_1
  - libxml2=2.13.5=h0b34f26_0
  - libzlib=1.2.13=hfb2fe0b_6
  - libzopfli=1.0.3=hc377ac9_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_1
  - mamba=2.0.5=h5837114_1
  - markupsafe=2.1.3=py312h80987f9_0
  - matplotlib-inline=0.1.6=py312hca03da5_0
  - menuinst=2.1.2=py312hca03da5_0
  - mistune=2.0.4=py312hca03da5_0
  - mpc=1.3.1=h80987f9_0
  - mpfr=4.2.1=h80987f9_0
  - mpmath=1.3.0=py312hca03da5_0
  - multidict=6.1.0=py312h80987f9_0
  - multiprocess=0.70.15=py312hca03da5_0
  - mysql=8.4.0=h3a6587f_1
  - nbclient=0.8.0=py312hca03da5_0
  - nbconvert=7.16.4=py312hca03da5_0
  - nbformat=5.10.4=py312hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=py312hca03da5_0
  - networkx=3.3=py312hca03da5_0
  - nlohmann_json=3.11.3=h00cdb27_1
  - nomkl=3.0=0
  - notebook=7.2.2=py312hca03da5_1
  - notebook-shim=0.2.3=py312hca03da5_0
  - numexpr=2.10.1=py312h5d9532f_0
  - numpy=1.26.4=py312h7f4fdc5_0
  - numpy-base=1.26.4=py312he047099_0
  - openjpeg=2.5.2=h54b8e55_0
  - openldap=2.6.4=he7ef289_0
  - openssl=3.5.4=h5503f6c_0
  - opentelemetry-api=1.37.0=py312hca03da5_0
  - orc=2.0.1=h937ddfc_0
  - overrides=7.4.0=py312hca03da5_0
  - packaging=24.1=py312hca03da5_0
  - pandas=2.2.2=py312hd77ebd4_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre2=10.42=hb066dcc_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=11.0.0=py312hfaf4e14_0
  - pip=24.2=py312hca03da5_0
  - platformdirs=3.10.0=py312hca03da5_0
  - plotly=5.24.1=py312h989b03a_0
  - pluggy=1.0.0=py312hca03da5_1
  - ply=3.11=py312hca03da5_1
  - prometheus_client=0.21.0=py312hca03da5_0
  - prompt-toolkit=3.0.43=py312hca03da5_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - propcache=0.2.0=py312h80987f9_0
  - psutil=5.9.0=py312h80987f9_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-cpuinfo=9.0.0=pyhd8ed1ab_1
  - pyarrow=19.0.0=py312h313beb8_1
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.6=py312h80987f9_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py312hca03da5_1
  - pyparsing=3.2.0=py312hca03da5_0
  - pyqt=5.15.10=py312h313beb8_0
  - pyqt5-sip=12.13.0=py312h80987f9_0
  - pysocks=1.7.1=py312hca03da5_0
  - pytables=3.8.0=py312h2ed9014_4
  - python=3.12.2=hdf0ec26_0_cpython
  - python-dateutil=2.9.0post0=py312hca03da5_2
  - python-fastjsonschema=2.20.0=py312hca03da5_0
  - python-json-logger=2.0.7=py312hca03da5_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python-xxhash=3.5.0=py312h80987f9_0
  - python.app=3=py312h80987f9_1
  - python_abi=3.12=5_cp312
  - pytorch=2.5.1=gpu_mps_py312h80af30b_202
  - pytz=2024.1=py312hca03da5_0
  - pyyaml=6.0.2=py312h80987f9_0
  - pyzmq=25.1.2=py312h313beb8_0
  - qt-main=5.15.2=h0917680_11
  - qtconsole=5.6.0=py312hca03da5_0
  - qtpy=2.4.1=py312hca03da5_0
  - re2=2022.04.01=hc377ac9_0
  - readline=8.2=h1a28f6b_0
  - referencing=0.30.2=py312hca03da5_0
  - regex=2024.11.6=py312h80987f9_0
  - reproc=14.2.5.post0=h5505292_0
  - reproc-cpp=14.2.5.post0=h286801f_0
  - requests=2.32.3=py312hca03da5_0
  - rfc3339-validator=0.1.4=py312hca03da5_0
  - rfc3986-validator=0.1.1=py312hca03da5_0
  - rpds-py=0.10.6=py312h2aea54e_1
  - ruamel.yaml=0.18.6=py312h80987f9_0
  - ruamel.yaml.clib=0.2.8=py312h80987f9_0
  - safetensors=0.4.5=py312h7805bc0_1
  - scikit-image=0.24.0=py312hd77ebd4_0
  - scikit-learn=1.5.2=py312h313beb8_0
  - send2trash=1.8.2=py312hca03da5_0
  - setuptools=75.1.0=py312hca03da5_0
  - simdjson=3.11.3=ha393de7_0
  - sip=6.7.12=py312h313beb8_0
  - six=1.16.0=pyhd3eb1b0_1
  - sleef=3.5.1=h80987f9_2
  - snappy=1.2.1=h313beb8_0
  - sniffio=1.3.0=py312hca03da5_0
  - soupsieve=2.5=py312hca03da5_0
  - spdlog=1.15.0=h096ffd4_0
  - sqlite=3.45.3=h80987f9_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.14.0=py312hca03da5_0
  - tenacity=9.0.0=py312hca03da5_0
  - terminado=0.17.1=py312hca03da5_0
  - threadpoolctl=3.5.0=py312h989b03a_0
  - tifffile=2023.4.12=py312hca03da5_0
  - tinycss2=1.2.1=py312hca03da5_0
  - tk=8.6.14=h6ba3021_0
  - tokenizers=0.20.1=py312he2d9c3e_1
  - tornado=6.4.1=py312h80987f9_0
  - tqdm=4.66.5=py312h989b03a_0
  - traitlets=5.14.3=py312hca03da5_0
  - transformers=4.45.2=py312hca03da5_0
  - truststore=0.8.0=py312hca03da5_0
  - typing_extensions=4.11.0=py312hca03da5_0
  - tzdata=2024b=h04d1e81_0
  - unicodedata2=15.1.0=py312h80987f9_0
  - urllib3=2.2.3=py312hca03da5_0
  - utf8proc=2.6.1=h80987f9_1
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py312hca03da5_2
  - websocket-client=1.8.0=py312hca03da5_0
  - wheel=0.44.0=py312hca03da5_0
  - widgetsnbextension=4.0.13=py312hca03da5_0
  - xxhash=0.8.0=h1a28f6b_3
  - xz=5.4.6=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - yaml-cpp=0.8.0=h313beb8_1
  - yarl=1.18.0=py312h80987f9_0
  - zeromq=4.3.5=h313beb8_0
  - zfp=1.0.0=h313beb8_0
  - zipp=3.21.0=py312hca03da5_0
  - zlib=1.2.13=hfb2fe0b_6
  - zlib-ng=2.0.7=h1a8c8d9_0
  - zstandard=0.23.0=py312h1a4646a_0
  - zstd=1.5.6=hfb09047_0
  - pip:
      - absl-py==2.3.0
      - alabaster==0.7.16
      - albumentations==1.4.3
      - altgraph==0.17.4
      - app-model==0.2.8
      - appdirs==1.4.4
      - astunparse==1.6.3
      - autograd==1.8.0
      - autograd-gamma==0.5.0
      - build==1.3.0
      - cachey==0.2.1
      - chardet==5.2.0
      - click==8.3.0
      - cloudpickle==3.1.1
      - dask==2025.10.0
      - dask-image==2024.5.3
      - deeplabcut==3.0.0rc13
      - dlclibrary==0.0.11
      - docstring-parser==0.17.0
      - docutils==0.17.1
      - einops==0.8.1
      - etils==1.13.0
      - ffmpeg==1.4
      - filterpy==1.4.5
      - flatbuffers==25.2.10
      - flexcache==0.3
      - flexparser==0.4
      - formulaic==1.1.1
      - freetype-py==2.5.1
      - gast==0.6.0
      - glfw==2.10.0
      - google-pasta==0.2.0
      - grpcio==1.73.1
      - h5py==3.14.0
      - heapdict==1.0.1
      - hmmlearn==0.3.3
      - hsluv==5.0.4
      - imageio-ffmpeg==0.6.0
      - imagesize==1.4.1
      - imgaug==0.4.0
      - importlib-resources==6.5.2
      - in-n-out==0.2.1
      - interface-meta==1.3.0
      - islp==0.4.0
      - keras==3.10.0
      - libclang==18.1.1
      - lifelines==0.30.0
      - lightning-utilities==0.14.3
      - llvmlite==0.46.0b1
      - locket==1.0.0
      - loguru==0.7.3
      - lxml==5.4.0
      - lxml-html-clean==0.4.3
      - macholib==1.16.3
      - magicgui==0.10.1
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - matplotlib==3.8.4
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - modulegraph==0.19.6
      - mujoco==3.3.7
      - namex==0.1.0
      - napari==0.4.18
      - napari-console==0.1.4
      - napari-deeplabcut==0.2.1.7
      - napari-plugin-engine==0.2.0
      - napari-svg==0.2.1
      - natsort==8.4.0
      - nibabel==5.3.2
      - npe2==0.7.9
      - nuitka==2.7.11
      - numba==0.63.0b1
      - numpydoc==1.5.0
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - opt-einsum==3.4.0
      - optree==0.16.0
      - ordered-set==4.1.0
      - partd==1.4.2
      - patsy==1.0.1
      - pdf2image==1.17.0
      - pims==0.7
      - pint==0.25
      - pooch==1.8.2
      - progressbar2==4.5.0
      - protobuf==5.29.5
      - psygnal==0.15.0
      - py2app==0.28.8
      - pycocotools==2.0.10
      - pyconify==0.2.1
      - pydantic==1.10.24
      - pydantic-compat==0.1.2
      - pygam==0.9.1
      - pyinstaller==6.14.2
      - pyinstaller-hooks-contrib==2025.5
      - pyopengl==3.1.10
      - pyproject-hooks==1.2.0
      - pyside6==6.10.0
      - pyside6-addons==6.10.0
      - pyside6-essentials==6.10.0
      - python-utils==3.9.1
      - pytorch-lightning==2.5.1.post0
      - qdarkstyle==3.1
      - rich==14.0.0
      - scipy==1.11.4
      - seaborn==0.13.2
      - shapely==2.1.2
      - shellingham==1.5.4
      - shiboken6==6.10.0
      - slicerator==1.1.0
      - snowballstemmer==3.0.1
      - sphinx==4.5.0
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - statsmodels==0.14.4
      - superqt==0.7.6
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - termcolor==3.1.0
      - timm==1.0.20
      - tomli-w==1.2.0
      - toolz==1.1.0
      - torch==2.9.0
      - torchmetrics==1.7.2
      - torchvision==0.24.0
      - typer==0.20.0
      - typing-extensions==4.12.2
      - vispy==0.12.2
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xlrd==2.0.2
prefix: /Users/chen/miniconda3
